create table if not exists public.cities
(
    id   bigserial
    primary key,
    name varchar(255) not null
    );

insert into public.cities (id, name)
values  (4, 'ADANA'),
        (5, 'ADIYAMAN'),
        (6, 'AFYONKARAHİSAR'),
        (7, 'AĞRI'),
        (8, 'AMASYA'),
        (9, 'ANKARA'),
        (10, 'ANTALYA'),
        (11, 'ARTVİN'),
        (12, 'AYDIN'),
        (13, 'BALIKESİR'),
        (14, 'BİLECİK'),
        (15, 'BİNGÖL'),
        (16, 'BİTLİS'),
        (17, 'BOLU'),
        (18, 'BURDUR'),
        (19, 'BURSA'),
        (20, 'ÇANAKKALE'),
        (21, 'ÇANKIRI'),
        (22, 'ÇORUM'),
        (23, 'DENİZLİ'),
        (24, 'DİYARBAKIR'),
        (25, 'EDİRNE'),
        (26, 'ELAZIĞ'),
        (27, 'ERZİNCAN'),
        (28, 'ERZURUM'),
        (29, 'ESKİŞEHİR'),
        (30, 'GAZİANTEP'),
        (31, 'GİRESUN'),
        (32, 'GÜMÜŞHANE'),
        (33, 'HAKKARİ'),
        (34, 'HATAY'),
        (35, 'ISPARTA'),
        (36, 'MERSİN'),
        (37, 'İSTANBUL'),
        (38, 'İZMİR'),
        (39, 'KARS'),
        (40, 'KASTAMONU'),
        (41, 'KAYSERİ'),
        (42, 'KIRKLARELİ'),
        (43, 'KIRŞEHİR'),
        (44, 'KOCAELİ'),
        (45, 'KONYA'),
        (46, 'KÜTAHYA'),
        (47, 'MALATYA'),
        (48, 'MANİSA'),
        (49, 'KAHRAMANMARAŞ'),
        (50, 'MARDİN'),
        (51, 'MUĞLA'),
        (52, 'MUŞ'),
        (53, 'NEVŞEHİR'),
        (54, 'NİĞDE'),
        (55, 'ORDU'),
        (56, 'RİZE'),
        (57, 'SAKARYA'),
        (58, 'SAMSUN'),
        (59, 'SİİRT'),
        (60, 'SİNOP'),
        (61, 'SİVAS'),
        (62, 'TEKİRDAĞ'),
        (63, 'TOKAT'),
        (64, 'TRABZON'),
        (65, 'TUNCELİ'),
        (66, 'ŞANLIURFA'),
        (67, 'UŞAK'),
        (68, 'VAN'),
        (69, 'YOZGAT'),
        (70, 'ZONGULDAK'),
        (71, 'AKSARAY'),
        (72, 'BAYBURT'),
        (73, 'KARAMAN'),
        (74, 'KIRIKKALE'),
        (75, 'BATMAN'),
        (76, 'ŞIRNAK'),
        (77, 'BARTIN'),
        (78, 'ARDAHAN'),
        (79, 'IĞDIR'),
        (80, 'YALOVA'),
        (81, 'KARABÜK'),
        (82, 'KİLİS'),
        (83, 'OSMANİYE'),
        (84, 'DÜZCE'),
        (85, 'LEFKOŞE (KIBRIS)'),
        (86, 'GİRNE (KIBRIS)'),
        (87, 'MAĞUSA (KIBRIS)');
